language: generic
dist: buster
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
before_script:
  - make -f old-Makefile
  - make -f old-Makefile test
script:
  - bin/test
notifications:
email: false
