language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
before_script:
  - FC=gfortran-7 cmake .
  - make 
  - make
script:
  - bin/simsphere_test
  - ctest
notifications:
email: false
