language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
before_script:
  - FC=gfortran-7 -DCMAKE_BUILD_TYPE=Debug cmake .
  - cmake --build .
script:
  - bin/test_snding
  - ctest
notifications:
email: false
after_success:
 - bash <(curl -s https://codecov.io/bash)
